scheduling_mode: "P_based"
blocks_spec:
  initial_num: 10
tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      initial_num: 100
      data_path: "multiblock_dpf_killer"
scheduler_spec:
  method: simplex