global_seed: 64
enable_random_seed: False

budget_accountant:
  epsilon: 10
  delta: 1e-7
  alphas:
  # - 1.5
  # - 1.75
  # - 2
  # - 2.25
  # - 2.5
  # - 2.75
  # - 3
  # - 3.25
  # - 3.5
  # - 3.75
  # - 4
  # - 4.5
  # - 5
  # - 6
  # - 8
  # - 16
  # - 32
  - 64
  # - 256
  # - 1_000
  # - 10_000


logs:
  verbose: False
  save: False
  mlflow: False
  loguru_level: "INFO"
