global_seed: 64

budget_accountant:
  epsilon: 10
  delta: 1e-7
  alphas:
  - 1.5
  - 1.75
  - 2
  - 2.5
  - 3
  - 4
  - 5
  - 6
  - 8
  - 16
  - 32
  - 64

blocks:
  initial_num: 1
  max_num: 10
  arrival_interval: 1

tasks:
  path: "tasks"
  initial_num: 1
  max_num: None

logs:
  verbose: False
  save: False
  mlflow: False
  loguru_level: "INFO"
