global_seed: 64
enable_random_seed: False

budget_accountant:
  epsilon: 10
  delta: 1e-7
  alphas:
  - 1.5
  - 1.75
  - 2
  - 2.5
  - 3
  - 4
  - 5
  - 6
  - 8
  - 16
  - 32
  - 64

logs:
  verbose: False
  save: False
  mlflow: False
  loguru_level: "INFO"
