log_file: "fcfs_example"

online:
  enabled: true

  blocks_spec:
    num: 3
    block_arrival_interval: 2

  tasks_spec:
    curve_distributions:
      laplace:
        frequency: 0.33
      gaussian:
        frequency: 0.34
      SubsampledGaussian:
        frequency: 0.33
    task_arrival_frequency:
      constant:
        enabled: true
        task_arrival_interval: 5
    blocks_request:
      #      constant:
      #        enabled: true
      #        blocks_num: 1
      random:
        enabled: true
        blocks_num_max: 3
  scheduler_spec:
    name: fcfs
