log_file: "dpf_example"

online:
  enabled: true

  blocks_spec:
    num: 1
    block_arrival_interval: 2

  tasks_spec:
    curve_distributions:
      laplace:
        frequency: 0.33
      gaussian:
        frequency: 0.34
      SubsampledGaussian:
        frequency: 0.33
    task_arrival_frequency:
      constant:
        enabled: true
        task_arrival_interval: 2
    blocks_request:
      constant:
        enabled: true
        blocks_num: 1
  scheduler_spec:
    name: dpf