log_file: "dominant_shares_offline_single_block_dpf_killer"

epsilon: 10
delta: 0.00001

blocks_spec:
  initial_num: 1

tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      initial_num: 10
      frequency: 1
      data_path: "single_block_dpf_killer"
      data_task_frequencies_path: "frequencies.yaml"

scheduler_spec:
  method: basic_scheduler
  metric: DominantShares