log_file: "mice_and_elephants_threshold_updating_flat_relevance"
scheduling_mode: "T_based"
epsilon: 10
delta: 1.0e-3

blocks_spec:
  initial_num: 10

tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      frequency: 1
      data_path: "mice_and_elephants"

  task_arrival_frequency:
    enabled: true
    poisson:
      enabled: true
      task_arrival_interval: 0.004264781

scheduler_spec:
  method: threshold_updating
  metric: flat_relevance
  shortest_time_window: 0.5
  threshold_update_mechanism: NaiveAverage