# log_file: "dpf_offline_multi_block_dpf_killer"

epsilon: 10
delta: 0.00001

blocks_spec:
  initial_num: 10

tasks_spec:
  curve_distributions:
    laplace:
      num: 100
      num_blocks: 3
      noise_start: 0.1
      noise_stop: 5
    gaussian:
      num: 100
      num_blocks: 4
      sigma_start: 1
      sigma_stop: 5
    SubsampledGaussian:
      num: 100
      num_blocks: 5
      sigma_start: 1
      sigma_stop: 5
      dataset_size: 60_000
      batch_size: 64
      epochs: 10
      
scheduler_spec:
  method: simplex
