log_file: "budget_unlocking_overflow_relevance"

blocks_spec:
  initial_num: 10

tasks_spec:
  curve_distributions:
    gaussian:
      frequency: 1
      blocks_request:
        random:
          enabled: true
          num_blocks_max: 10

  task_arrival_frequency:
    enabled: true
    constant:
      enabled: true
      task_arrival_interval: 5

scheduler_spec:
  method: budget_unlocking
  metric: overflow_relevance
  n: 1000