log_file: "fcfs"

blocks_spec:
  initial_num: 3
  block_arrival_frequency:
    enabled: true    # no online blocks
    poisson:
      enabled: false
      block_arrival_interval: 4
    constant:
      enabled: true
      block_arrival_interval: 1

tasks_spec:
  curve_distributions:
    laplace:
      frequency: 0.33
      blocks_request:
        random:
          enabled: true
          num_blocks_max: 3

    gaussian:
      frequency: 0.34
      blocks_request:
        random:
          enabled: true
          num_blocks_max: 3

    SubsampledGaussian:
      frequency: 0.33
      blocks_request:
        random:
          enabled: true
          num_blocks_max: 3

  task_arrival_frequency:
    enabled: true
    constant:
      enabled: true
      task_arrival_interval: 5

scheduler_spec:
  metric: fcfs
