log_file: "multiblock_dpf_killer_threshold_updating_flat_relevance"

blocks_spec:
  initial_num: 10
  block_arrival_frequency:
    enabled: true
    constant:
      enabled: true
      block_arrival_interval: 1
tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      frequency: 1
      data_path: "multiblock_dpf_killer"
      data_task_frequencies_path: "frequencies.yaml"

  task_arrival_frequency:
    enabled: true
    poisson:
      enabled: true
      task_arrival_interval: 0.004264781

scheduler_spec:
  method: threshold_updating
  metric: flat_relevance
  shortest_time_window: 120
  threshold_update_mechanism: NaiveAverage