log_file: "multiblock_dpf_killer_threshold_updating_flat_relevance"
scheduling_mode: "T_based"

blocks_spec:
  initial_num: 10

tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      frequency: 1
      data_path: "multiblock_dpf_killer"

  task_arrival_frequency:
    enabled: true
    constant:
      enabled: true
      task_arrival_interval: 5

scheduler_spec:
  method: threshold_updating
  metric: flat_relevance
  shortest_time_window: 120
  threshold_update_mechanism: QueueAverageDynamic