scheduler: 
  metric_recomputation_period: 1
  log_warning_every_n_allocated_tasks: 0
  
metric:
  normalize_by: ""
  temperature: 1
  gurobi_timeout: 200
  gurobi_threads: 1
  rescale_profits: True
  polynomial_ratio: False
  clip_demands_in_relevance: False

logs:
  verbose: False
  save: False


alphas:
- 1.5
- 1.75
- 2
- 2.5
- 3
- 4
- 5
- 6
- 8
- 16
- 32
- 64