scheduler: 
  method: offline
  metric: DominantShares
  n: 100
  budget_unlocking_time: 1
  solver: gurobi
  scheduling_wait_time: 1
  data_lifetime: 10
  metric_recomputation_period: 1
  log_warning_every_n_allocated_tasks: 0
  scheduler_timeout_seconds: 0
  
metric:
  normalize_by: ""
  temperature: 1
  gurobi_timeout: 200
  gurobi_threads: 1
  n_knapsack_solvers: 1
  rescale_profits: True
  polynomial_ratio: False
  clip_demands_in_relevance: False
  save_profit_matrix: False

logs:
  verbose: False
  save: False


alphas:
- 1.5
- 1.75
- 2
- 2.5
- 3
- 4
- 5
- 6
- 8
- 16
- 32
- 64