log_file: "simplex"

blocks_spec:
  initial_num: 5

tasks_spec:
  curve_distributions:
    laplace:
      initial_num: 100
      noise_start: 0.1
      noise_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 3
      block_selecting_policy: LatestBlocksFirst

    gaussian:
      initial_num: 100
      sigma_start: 1
      sigma_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 3
      block_selecting_policy: LatestBlocksFirst

    SubsampledGaussian:
      initial_num: 100
      sigma_start: 1
      sigma_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 3
      block_selecting_policy: LatestBlocksFirst

scheduler_spec:
  name: simplex
