log_file: "simplex_offline_multi_block_dpf_killer"

epsilon: 10
delta: 0.00001

blocks_spec:
  initial_num: 10

tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      initial_num: 100
      frequency: 1
      data_path: "multiblock_dpf_killer"
      data_task_frequencies_path: "frequencies.yaml"
      read_block_selecting_policy_from_config:
        enabled: true
        block_selecting_policy: RandomBlocks

scheduler_spec:
  method: simplex