scheduler:
  metric: DominantShares
  method: batch
  log_warning_every_n_allocated_tasks: 10

blocks:
  initial_num: 10
  max_num: 50

tasks:
  data_path: alibaba-privacy-workload/outputs/privacy_tasks.csv
  sampling: ""

logs:
  verbose: False
  save: True