blocks_spec:
  offline:
    enabled: true
    num: 2

tasks_spec:
  offline:
    enabled: true
    curve_distributions:
      laplace:
        num: 5
        num_blocks: 1

      gaussian:
        num: 5
        num_blocks: 1

      SubsampledGaussian:
        num: 5
        num_blocks: 1