scheduler: 
  method: offline
  metric: DominantShares
  n: 100
  budget_unlocking_time: 1
  solver: gurobi
  scheduling_wait_time: 1
  data_lifetime: 10
  task_lifetime: 10
  max_substitutes_allowed: 10
  metric_recomputation_period: 1
  log_warning_every_n_allocated_tasks: 0
  scheduler_timeout_seconds: 0
  
metric:
  normalize_by: ""
  temperature: 1
  gurobi_timeout: 200
  gurobi_threads: 1
  n_knapsack_solvers: 1
  rescale_profits: True
  polynomial_ratio: False
  clip_demands_in_relevance: False
  save_profit_matrix: False

blocks:
  initial_num: 1
  max_num: 10

tasks:
  data_path: "heterogeneous"
  frequencies_path: "frequencies.yaml"
  tasks_path: "tasks"
  initial_num: 100

  # One of: poisson, constant. If empty, will attempt to read tasks from a csv file.
  sampling: "poisson"
  avg_num_tasks_per_block: 100

  # Set to RandomBlocks or LatestBlocksFirst for instance.
  # Will override the selection given by individual tasks specs.
  # Leave empty to follow the tasks specs.
  block_selection_policy: ""

logs:
  verbose: False
  save: False

alphas:
- 1.5
- 1.75
- 2
- 2.5
- 3
- 4
- 5
- 6
- 8
- 16
- 32
- 64

epsilon: 10
delta: 0.00001
global_seed: 64
k: 0.25