renyi_epsilon: 10
renyi_delta: 1e-8
#alphas: [1.5, 1.75, 2, 2.5, 3, 4, 5, 6, 8, 16, 32, 64]
plot_file: "privacypacking/plots/plotfile.pickle"
default_plot_file: "privacypacking/config/default_config.yaml"

offline:
  enabled: false

  blocks_spec:
    num: 1

  tasks_spec:
    curve_distributions:
      laplace:
        num: 0
        num_blocks: 1
        noise_start: 0.1
        noise_stop: 10
      gaussian:
        num: 0
        num_blocks: 1
        sigma_start: 1
        sigma_stop: 10
      SubsampledGaussian:
        num: 0
        num_blocks: 1
        sigma_start: 1
        sigma_stop: 10
        dataset_size: 60_000
        batch_size: 64
        epochs: 10
  scheduler_spec:
    name: simplex

online:
  enabled: false

  blocks_spec:
    num: 1
    block_arrival_interval: 2

  tasks_spec:
    curve_distributions:
      laplace:
        frquency: 0
        num_blocks: 1
        noise_start: 0.1
        noise_stop: 10
      gaussian:
        frquency: 0
        num_blocks: 1
        sigma_start: 1
        sigma_stop: 10
      SubsampledGaussian:
        frquency: 0
        num_blocks: 1
        sigma_start: 1
        sigma_stop: 10
        dataset_size: 60_000
        batch_size: 64
        epochs: 10
    task_arrival_frequency:
      poisson:
        enabled: false
        random_seed: 44
        task_arrival_interval: 0.004264781
      constant:
        enabled: false
        task_arrival_interval: 2
    blocks_request:
      random:
        enabled: false
          random_seed: 44
          blocks_num_max: 10
      constant:
        enabled: false
          blocks_num: 1
    block_selecting_policy: "latest_first"

  scheduler_spec:
    name: fcfs
    n: 100



