tasks_spec:
  curve_distributions:
    # Reading tasks from files
    custom:
      sampling: false # If true we sample uniformly tasks from the data_path else we read the tasks sequentially
      initial_num: 0
      data_path: ""
      data_task_frequencies_path: ""
      read_block_selecting_policy_from_config:
        enabled: false
        block_selecting_policy: RandomBlocks

  task_arrival_frequency:
    enabled: false  # no online tasks
    poisson:
      enabled: false
      avg_number_tasks_per_block: 100
    constant:
      enabled: false
      avg_number_tasks_per_block: 100
    actual:       # Actual arrival time of custom tasks
      enabled: false
