epsilon: 10
delta: 0.001
#alphas: [1.5, 1.75, 2, 2.5, 3, 4, 5, 6, 8, 16, 32, 64]
#log_file: "privacypacking/logs/plotfile.pickle"
#default_config_file: "privacypacking/config/default_config.yaml"
global_seed: 44
deterministic: true

blocks_spec:
  initial_num: 1
  block_arrival_frequency:
    enabled: false    # no online blocks
    poisson:
      enabled: false
      block_arrival_interval: 4
    constant:
      enabled: false
      block_arrival_interval: 4

tasks_spec:
  curve_distributions:
    laplace:
      initial_num: 0
      frequency: 0
      noise_start: 0.1
      noise_stop: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "latest_first"

    gaussian:
      initial_num: 0
      frequency: 0
      sigma_start: 1
      sigma_stop: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "latest_first"

    SubsampledGaussian:
      initial_num: 0
      frequency: 0
      sigma_start: 1
      sigma_stop: 10
      dataset_size: 60_000
      batch_size: 64
      epochs: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "latest_first"

  task_arrival_frequency:
    enabled: false  # no online tasks
    poisson:
      enabled: false
      task_arrival_interval: 0.004264781
    constant:
      enabled: false
      task_arrival_interval: 2


scheduler_spec:
  name: fcfs
  n: 100