# TODO: we need to clean this
scheduler: 
  method: offline
  metric: DominantShares
  n: 100
  solver: gurobi
  scheduling_wait_time: 1
  data_lifetime: 10
  task_lifetime: 10
  metric_recomputation_period: 1
  log_warning_every_n_allocated_tasks: 0
  scheduler_timeout_seconds: 0
  demands_tiebreaker: 0
  
metric:
  normalize_by: ""
  temperature: 1
  gurobi_timeout: 200
  gurobi_threads: 1
  n_knapsack_solvers: 1
  rescale_profits: True
  polynomial_ratio: False
  clip_demands_in_relevance: False
  save_profit_matrix: False

blocks:
  initial_num: 1
  max_num: 10

tasks:
  path: "tasks"
  initial_num: 100
  sampling: ""
  max_num: 100

logs:
  verbose: False
  save: False
  mlflow: False

alphas:
- 1.5
- 1.75
- 2
- 2.5
- 3
- 4
- 5
- 6
- 8
- 16
- 32
- 64

epsilon: 10
delta: 1e-7
global_seed: 64