epsilon: 10
delta: 0.00001
global_seed: 64
deterministic: true
log_every_n_iterations: 0
profit: 1

blocks_spec:
  initial_num: 1
  max_blocks: 10
  block_arrival_frequency:
    enabled: false    # no online blocks
    poisson:
      enabled: false
      block_arrival_interval: 4
    constant:
      enabled: false
      block_arrival_interval: 4

tasks_spec:
  curve_distributions:
    # Reading tasks from files
    custom:
      sampling: false # If true we sample uniformly tasks from the data_path else we read the tasks sequentially
      initial_num: 0
      frequency: 0
      data_path: ""
      data_task_frequencies_path: ""
      read_block_selecting_policy_from_config:
        enabled: false
        block_selecting_policy: RandomBlocks

  task_arrival_frequency:
    enabled: false  # no online tasks
    poisson:
      enabled: false
      task_arrival_interval: 0.004264781
    constant:
      enabled: false
      task_arrival_interval: 2
    actual:       # Actual arrival time of custom tasks
      enabled: false
      task_arrival_interval: None

scheduler_spec:
  method: n_budget_unlocking
  metric: DominantShares
  n: 100
  budget_unlocking_time: 1
  solver: gurobi
  scheduling_wait_time: 1
  threshold_update_mechanism: NaiveAverage
