epsilon: 10
delta: 0.001
global_seed: 44
deterministic: true
log_every_n_iterations: 0
scheduling_mode: "P_based"     # Other option: T_based
number_of_queues: 1
profit: 1

blocks_spec:
  initial_num: 1
  block_arrival_frequency:
    enabled: false    # no online blocks
    poisson:
      enabled: false
      block_arrival_interval: 4
    constant:
      enabled: false
      block_arrival_interval: 4

tasks_spec:
  curve_distributions:
    # Reading tasks from files
    custom:
      sampling: false # If true we sample uniformly tasks from the data_path else we read the tasks sequentially
      initial_num: 0
      frequency: 0
      data_path: ""

    # Sampling from a laplace
    laplace:
      initial_num: 0
      frequency: 0
      noise_start: 0.1
      noise_stop: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "latest_blocks_first"

    # Sampling from a gaussian
    gaussian:
      initial_num: 0
      frequency: 0
      sigma_start: 1
      sigma_stop: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "random_blocks"

    # Sampling from a SubsampledGaussian
    SubsampledGaussian:
      initial_num: 0
      frequency: 0
      sigma_start: 1
      sigma_stop: 10
      dataset_size: 60_000
      batch_size: 64
      epochs: 10
      blocks_request:
        random:
          enabled: false
          num_blocks_max: 10
        constant:
          enabled: false
          num_blocks: 1
      block_selecting_policy: "latest_blocks_first"

  task_arrival_frequency:
    enabled: false  # no online tasks
    poisson:
      enabled: false
      task_arrival_interval: 0.004264781
    constant:
      enabled: false
      task_arrival_interval: 2


scheduler_spec:
  name: basic_scheduler
  metric: fcfs
  n: 100
  shortest_time_window: 20
  threshold_update_mechanism: queue_average_static