online:
  enabled: true

  blocks_spec:
    num: 1
    block_arrival_interval: 2

  tasks_spec:
    curve_distributions:
      laplace:
        frequency: 0.33
        num_blocks: 1
      gaussian:
        frequency: 0.33
        num_blocks: 1
      SubsampledGaussian:
        frequency: 0.33
        num_blocks: 1
    task_arrival_frequency:
      constant:
        enabled: false
        task_arrival_interval: 2
    block_request:
      constant:
        enabled: true
          blocks_num: 1

  scheduler_spec:
    name: dpf
    #    name: fcfs
    n: 15000