blocks_spec:
  num: 3

tasks_spec:
  curve_distributions:
    laplace:
      initial_num: 85
      noise_start: 0.1
      noise_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 3

    gaussian:
      initial_num: 85
      sigma_start: 1
      sigma_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 4

    SubsampledGaussian:
      initial_num: 85
      sigma_start: 1
      sigma_stop: 5
      blocks_request:
        constant:
          enabled: true
          num_blocks: 5

scheduler_spec:
  name: OfflineDPF