offline:
  enabled: true

  blocks_spec:
    num: 1

  tasks_spec:
    curve_distributions:
      laplace:
        num: 5
        num_blocks: 1
      gaussian:
        num: 5
        num_blocks: 1
      SubsampledGaussian:
        num: 5
        num_blocks: 1

  scheduler_spec:
    name: simplex