# log_file: "simplex_example"
offline:
  enabled: true

  blocks_spec:
    num: 10

  tasks_spec:
    curve_distributions:
      laplace:
        num: 1000
        num_blocks: 3
      gaussian:
        num: 50
        num_blocks: 5
      SubsampledGaussian:
        num: 100
        num_blocks: 7

  scheduler_spec:
    name: OverflowRelevance