blocks_spec:
  offline:
    enabled: true
    num: 1

tasks_spec:
  offline:
    enabled: true
    curve_distributions:
      laplace:
        num: 0
        num_blocks: 1

      gaussian:
        num: 10
        num_blocks: 1

      SubsampledGaussian:
        num: 0
        num_blocks: 1

  scheduler: simplex
