blocks_spec:
  offline:
    enabled: true
    num: 2

tasks_spec:
  online:
    enabled: true
    curve_distributions:
      laplace:
        frequency: 0.33
        num_blocks: 1

      gaussian:
        frequency: 0.33
        num_blocks: 1

      SubsampledGaussian:
        frequency: 0.33
        num_blocks: 1

scheduler: "fcfs"