epsilon: 5
delta: 1.0e-5

blocks_spec:
  initial_num: 10
  max_blocks: 30
  block_arrival_frequency:
    enabled: true
    constant:
      enabled: true
      block_arrival_interval: 1

tasks_spec:
  curve_distributions:
    custom:
      sampling: False
      data_path: "alibaba-privacy-workload/outputs/privacy_tasks.csv"

  task_arrival_frequency:
    enabled: true
    actual:
      enabled: true

scheduler_spec:
  method: time_based_budget_unlocking
  data_lifetime: 10
  metric: DominantShares
  n: 125