tasks_spec:
  curve_distributions:
    custom:
      sampling: true
      frequency: 1
      data_path: "mixed_curves"
      data_task_frequencies_path: "frequencies.yaml"

  task_arrival_frequency:
    enabled: true
    poisson:
      enabled: true
      avg_number_tasks_per_block: 250